#!/bin/bash

file=""

case $1 in
    vim|vi|nvim)
        file=$XDG_CONFIG_HOME/nvim/init.vim;;

    aw|awm|awesome|awesomewm)
        if [ -z $2 ]
        then
            file=$XDG_CONFIG_HOME/awesome/rc.lua
        else
            file=$XDG_CONFIG_HOME/awesome/$2
        fi;;

    ala|alacritty)
        file=$XDG_CONFIG_HOME/alacritty.yml;;

    z|zsh)
        file=$HOME/.zshrc;;
    ssh)
        file=$HOME/.ssh/config;;
    '')
        echo "USAGE: conf <config name>";exit 0;;
esac

if [ ! $file = "" ]
then
    $EDITOR $file
else
    exit 1
fi
